### ISSUE TITLE
nmp run start 错误

### ISSUE THREAD

**Issue by Awelling2** [HualuozhE/YunKeTangZhiHuiZhiJiao-Crack#1]
Ubuntu报错，Windows下用git可以npm

> npm ERR! Linux 2.6.32-042stab128.2
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! YunKeTang@1.0.0 start: `node ./index.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the YunKeTang@1.0.0 start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the YunKeTang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs YunKeTang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls YunKeTang
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/sk/YunKeTangZhiHuiZhiJiao-Crack/npm-debug.log

**Comment by HualuozhE** [comment]
请尝试升级nodejs和npm的版本

**Comment by sjl88888888** [comment]
d:\新建文件夹\YunKeTangZhiHuiZhiJiao-Crack-master>npm run start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path d:\新建文件夹\YunKeTangZhiHuiZhiJiao-Crack-master\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'd:\新建文件夹\YunKeTangZhiHuiZhiJiao-Crack-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\86235\AppData\Roaming\npm-cache\_logs\2020-02-27T12_06_50_754Z-debug.log
