### ISSUE TITLE
课全部刷完，但课程未显示100%

### ISSUE THREAD

**Issue by leijux** [HualuozhE/YunKeTangZhiHuiZhiJiao-Crack#4]
可能是请求太快，服务器响应不过来，希望可以慢一点。另外作者可以提供一下制作思路嘛，感激不尽！

**Comment by HualuozhE** [comment]
你课程看完时，云课堂会往服务器发送一个http请求，程序就是在模拟相同的操作而已。卡进度问题，这个是真的云课堂的bug，人家的bug，我来给他修复，非常难受。

**Comment by leijux** [comment]
懂了，谢谢。
